FROM python:3.10-slim
WORKDIR /app

COPY api/api_transformer ./api_transformer
COPY models/transformer ./models/transformer

RUN pip install --no-cache-dir fastapi uvicorn torch transformers

EXPOSE 8002
CMD ["uvicorn", "api_transformer.main:app", "--host", "0.0.0.0", "--port", "8002"]
