FROM python:3.10
WORKDIR /app

COPY api/api_transformer ./api_transformer

# Python 3.10 a déjà les dépendances système nécessaires
RUN pip install \
    fastapi \
    uvicorn \
    transformers \
    torch

EXPOSE 8002
CMD ["uvicorn", "api_transformer.main:app", "--host", "0.0.0.0", "--port", "8002"]